org.gradle.jvmargs=-Xmx3g -XX:+UseParallelGC --add-opens jdk.compiler/com.sun.tools.javac.model=ALL-UNNAMED
systemProp.file.encoding=utf-8

# https://docs.gradle.org/current/userguide/configuration_cache.html
org.gradle.configuration-cache=true

# https://kotlinlang.org/docs/native-target-support.html
kotlin.native.ignoreDisabledTargets=true

# faster builds: build modules in parallel and reuse task outputs from the build cache
org.gradle.parallel=true
org.gradle.caching=true
kotlin.incremental=true
kotlin.daemon.jvmargs=-Xmx2g
